name: Build Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build APK with buildozer
        uses: Artemiz/buildozer-action@v1
        with:
          buildozer_target: android debug

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: output-apk
          path: bin/*.apk
